### ISSUE TITLE
[EtcdAPI][Feature]: Support set version?

### ISSUE THREAD

**Issue by liangyuanpeng** [xline-kv/Xline#867]
### Description about the feature

kubernetes 1.31(master)  will begin to require a certain version of etcd to use some feature, and xline has its own version number, which means that if the xline's `Maintenance.Status` request returns a version number that does not correspond to etcd, it will never run in this case. 

https://github.com/kubernetes/kubernetes/blob/8cf93c8d83df3a206ab4abe2ed2ead7a173bd63e/staging/src/k8s.io/apiserver/pkg/storage/feature/feature_support_checker.go#L157-L172

[cilium ](https://github.com/cilium/cilium) also have the same problem.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CrystalAnalyst** [comment]
Thanks for the considerate suggesion! 
Since our project already supports the `RequestWatchProgress` function, indicating that Xline already has the necessary compatibility for systems such as Kubernetes that rely on this function. 
This means that if Xline is used as an etcd replacement, it can meet the requirements for Kubernetes ,
compatible with etcd 3.5.13(and above) without the need for specific compatibility.

**Comment by liangyuanpeng** [comment]
Hi @CrystalAnalyst , sorry for not clear it, kubernetes/ cilium will check the version with grpc api `Maintenance.Status`.

for example:
1. kubernetes/cilium get the version 3.5 with grpc api   `Maintenance.Status`
2.  if version <3.5, exit the program or prompt that the feature is not supported.
  2.1) etcd return 3.5.15, success running
  2.2) xline return 0.6.1,  failed running
  
  
 So this issue is requesting for xline can return the special version from grpc api and not the really xline version (0.6.1).

 Remind me if i have not clear it.

**Comment by liangyuanpeng** [comment]
no stale
