### ISSUE TITLE
Is there an xline WeChat communication group?

### ISSUE THREAD

**Issue by wking1986** [xline-kv/Xline#959]
### Description about the bug

Is there an xline WeChat communication group?

### Version

0.1.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Phoenix500526** [comment]
Hi, @wking1986 , sorry for the delay reply. Currently, Xline doesn't have a WeChat group. Since Xline is primarily global-focused at the moment, communication is mainly conducted through Discord. In the future, if there are enough Chinese developers in the community, we may consider creating a WeChat group.

**Comment by wking1986** [comment]
Thank you for your reply. Can you share a Discord **xline** invitation code?

**Comment by liangyuanpeng** [comment]
> Thank you for your reply. Can you share a Discord xline invitation code?

@wking1986  check the README https://github.com/xline-kv/Xline?tab=readme-ov-file#scope

**Comment by wking1986** [comment]
Get！Thanks！！
